server:
  port: 8888
  servlet:
    #开启热部署
    jsp:
      init-parameters:
        development: true
#banner文件设置
spring:
  banner:
    charset: UTF-8
    image:
      location: banner.txt
  ##设置上传文件的大小
  servlet:
    multipart:
      max-file-size: 100MB  #设置单个文件最大长度
      max-request-size: 100MB  #最大请求文件的大小
  redis:
    host: 192.168.11.129
    port: 7070
    database: 3
  #数据库连接池
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/yingxue?useUnicode=true&characterEncoding=utf8
#起别名
mybatis:
  type-aliases-package: com.baizhi.entity
  #注册mapper文件
  mapper-locations: classpath:com/baizhi/mapper/*Mapper.xml
